CREATE TABLE AuditLog (
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    AccountID NUMBER,
    Amount NUMBER,
    TransactionType VARCHAR2(20),
    LogDate DATE
);
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN

    INSERT INTO AuditLog(
        TransactionID,
        AccountID,
        Amount,
        TransactionType,
        LogDate
    )
    VALUES(
        :NEW.TransactionID,
        :NEW.AccountID,
        :NEW.Amount,
        :NEW.TransactionType,
        SYSDATE
    );

END;
/

INSERT INTO Transactions
VALUES (2, 1, SYSDATE, 500, 'Deposit');

INSERT INTO Transactions
VALUES (3, 2, SYSDATE, 1000, 'Withdrawal');

INSERT INTO Transactions
VALUES (4, 1, SYSDATE, 750, 'Deposit');

INSERT INTO Transactions
VALUES (5, 2, SYSDATE, 300, 'Withdrawal');
